name: Test Gem
description: Tests a specific Gem
inputs:
  gem:
    description: Gem to test
    required: true
    type: string
  ruby:
    description: Ruby version to use
    required: true
    type: string
  yard:
    description: Run YARD documentation
    required: false
    type: boolean
    default: false
  rubocop:
    description: Run Rubocop
    required: false
    type: boolean
    default: false
  build:
    description: Build gem
    required: false
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Setup
      id: setup
      shell: bash
      run: |
        dir=$(find . -iname '${{ inputs.gem }}.gemspec' -exec dirname {} \;)
        echo "::set-output name=dir::${dir}"

        # We install multiple ruby versions here, and that makes for some
        # annoying bundler conflicts when we get to the JRuby step. Removing
        # the lockfile slows things down a bit, but we should still get most
        # of the benefits of bundler caching.
        rm -f "${dir}/Gemfile.lock"

        echo "::set-output name=cache_key::linux"
        if [[ "${{ inputs.ruby }}" == "jruby" ]]; then
          echo "::set-output name=cache_key::jruby"
        fi

        echo "::set-output name=appraisals::false"
        if [[ -f "${dir}/Appraisals" ]]; then
          echo "::set-output name=appraisals::true"
        fi

    - name: "Install Ruby ${{ inputs.ruby }} with dependencies"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ inputs.ruby }}"
        working-directory: "${{ steps.setup.outputs.dir }}"
        bundler-cache: true
        cache-version: "v1-${{ steps.setup.outputs.cache_key }}"

    # If we're using appraisal, installing those dependencies can
    # take quite awhile (looking at you, rdkafka). In order to shave
    # several minutes off of our builds, we attempt to cache the appraisal
    # stuff ourselves. :fingers_crossed:
    - name: "Generate Appraisal gemfiles"
      if: "${{ steps.setup.outputs.appraisals == 'true' }}"
      shell: bash
      run: |
        cd "${{ steps.setup.outputs.dir }}"

        # Remove generated lockfiles from previous builds, if they exist.
        bundle exec appraisal clean

        # Generate new Gemfiles
        bundle exec appraisal generate

        # Generate a lockfile for each one
        for gemfile in gemfiles/*; do
          BUNDLE_GEMFILE="gemfiles/${gemfile}" bundle lock --lockfile="gemfiles/${gemfile}.lock"
        done

    # Now, try to use a cache for actually installing things here...
    - name: "Cache Appraisal gems"
      if: "${{ steps.setup.outputs.appraisals == 'true' }}"
      uses: actions/cache@v3
      with:
        path: vendor/appraisal
        # This will almost certainly break anytime the `ubuntu-latest` version changes, and we'll need to bust the cache at that time. :(
        # Also take note of the dire warnings from the ruby/setup-ruby folks, which resulted in the "how to cache ruby w/ actions/cache" instructions
        # being removed entirely: https://github.com/actions/cache/commit/1bfe3accb30cbecd1eb79cdba246c3a7fc899cdf
        # We're not specifying a list of less-specific restore-keys here, because we're trying to be rather cautious. I'd rather have more
        # cache misses than deal with caching-related build failures more often than we have to.
        key: "v1-${{ runner.os }}-${{ steps.setup.outputs.cache_key }}-${{ inputs.ruby }}-${{ inputs.gem }}-${{ hashFiles('gemfiles/**.lock') }}"

    - name: "Install dependencies and appraisals"
      if: "${{ steps.setup.outputs.appraisals == 'true' }}"
      shell: bash
      run: |
        cd "${{ steps.setup.outputs.dir }}"
        bundle exec appraisal install --path vendor/appraisal

    - name: Test Gem
      shell: bash
      run: |
        cd "${{ steps.setup.outputs.dir }}"

        if [[ -f "Appraisals" ]]; then
          bundle exec appraisal rake test
        else
          bundle exec rake test
        fi
      env:
        TEST_KAFKA_HOST: "127.0.0.1"
        TEST_KAFKA_PORT: 29092
        TEST_MYSQL_HOST: "127.0.0.1"
        TEST_MYSQL_PORT: 3306
        TEST_MYSQL_USER: mysql
        TEST_MYSQL_PASSWORD: mysql
        TEST_POSTGRES_PASSWORD: postgres
        TEST_POSTGRES_USER: postgres
        TEST_POSTGRES_HOST: localhost
        TEST_POSTGRES_PORT: 5432
        TEST_POSTGRES_DB: postgres
        TEST_MEMCACHED_HOST: localhost
        TEST_MEMCACHED_PORT: 11211
        TEST_MONGODB_HOST: localhost
        TEST_MONGODB_PORT: 27017
        TEST_RABBITMQ_HOST: localhost
        TEST_RABBITMQ_PORT: 5672
        TEST_RABBITMQ_URL: amqp://guest:guest@localhost:5672
        TEST_REDIS_HOST: localhost
        TEST_REDIS_PORT: 6379

    - name: YARD
      shell: bash
      if: "${{ inputs.yard == 'true' }}"
      run: |
        cd "${{ steps.setup.outputs.dir }}"
        bundle exec rake yard

    - name: Rubocop
      shell: bash
      if: "${{ inputs.rubocop == 'true' }}"
      run: |
        cd "${{ steps.setup.outputs.dir }}"
        bundle exec rake rubocop

    - name: Build Gem
      shell: bash
      if: "${{ inputs.build == 'true' }}"
      run: |
        cd "${{ steps.setup.outputs.dir }}"
        gem build ${{ inputs.gem }}.gemspec
