name: Test Gem
description: Run CI for a specific opentelemetry-ruby gem
inputs:
  gem:
    description: Gem to test
    required: true
runs:
  using: "composite"
  steps:
    - name: Install gem
      shell: bash
      run: |
        dir=$(find . -iname "${{ matrix.gem }}*.gemspec" -exec dirname {} \;)
        cd "${dir}"

        bundle install --jobs=3 --retry=3

        if [[ -f Appraisals ]]; then
          bundle exec appraisal install
        fi
    - name: Run tests
      env:
        TEST_KAFKA_HOST: "127.0.0.1"
        TEST_KAFKA_PORT: 29092
        TEST_MYSQL_HOST: "127.0.0.1"
        TEST_MYSQL_PORT: 3306
        TEST_MYSQL_USER: mysql
        TEST_MYSQL_PASSWORD: mysql
        TEST_POSTGRES_PASSWORD: postgres
        TEST_POSTGRES_USER: postgres
        TEST_POSTGRES_HOST: localhost
        TEST_POSTGRES_PORT: 5432
        TEST_POSTGRES_DB: postgres
        TEST_MEMCACHED_HOST: localhost
        TEST_MEMCACHED_PORT: 11211
        TEST_MONGODB_HOST: localhost
        TEST_MONGODB_PORT: 27017
        TEST_RABBITMQ_HOST: localhost
        TEST_RABBITMQ_PORT: 5672
        TEST_RABBITMQ_URL: amqp://guest:guest@localhost:5672
        TEST_REDIS_HOST: localhost
        TEST_REDIS_PORT: 6379
      shell: bash
      run: |
        dir=$(find . -iname "${{ matrix.gem }}*.gemspec" -exec dirname {} \;)
        cd "${dir}"

        if [[ -f Appraisals ]]; then
          bundle exec appraisal rake test
        else
          bundle exec rake test
        fi
    - name: Rubocop
      shell: bash
      run: |
        dir=$(find . -iname "${{ matrix.gem }}*.gemspec" -exec dirname {} \;)
        cd "${dir}"

        bundle exec rake rubocop
    - name: YARD
      shell: bash
      run: |
        dir=$(find . -iname "${{ matrix.gem }}*.gemspec" -exec dirname {} \;)
        cd "${dir}"

        bundle exec rake yard
    - name: Build Gem
      shell: bash
      run: |
        dir=$(find . -iname "${{ matrix.gem }}*.gemspec" -exec dirname {} \;)
        cd "${dir}"

        gem build ${{ matrix.gem }}.gemspec
