name: Test Gem
description: Tests a specific Gem
inputs:
  gem:
    description: Gem to test
    required: true
    type: string
  ruby:
    description: Ruby version to use
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Locate Gemfile
      id: locate_gem
      shell: bash
      run: |
        dir=$(find . -iname '${{ inputs.gem }}.gemspec' -exec dirname {} \;)
        echo "::set-output name=dir::${dir}"
    - name: "Install Ruby ${{ inputs.ruby }}"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ inputs.ruby }}"
        working-directory: "${{ steps.locate_gem.outputs.dir }}"
        bundler-cache: true
        cache-version: "v1-${{ inputs.ruby }}"
    - name: Test Gem
      shell: bash
      run: |
        cd "${{ steps.locate_gem.outputs.dir }}"
        bundle exec rake test
      env:
        TEST_KAFKA_HOST: "127.0.0.1"
        TEST_KAFKA_PORT: 29092
        TEST_MYSQL_HOST: "127.0.0.1"
        TEST_MYSQL_PORT: 3306
        TEST_MYSQL_USER: mysql
        TEST_MYSQL_PASSWORD: mysql
        TEST_POSTGRES_PASSWORD: postgres
        TEST_POSTGRES_USER: postgres
        TEST_POSTGRES_HOST: localhost
        TEST_POSTGRES_PORT: 5432
        TEST_POSTGRES_DB: postgres
        TEST_MEMCACHED_HOST: localhost
        TEST_MEMCACHED_PORT: 11211
        TEST_MONGODB_HOST: localhost
        TEST_MONGODB_PORT: 27017
        TEST_RABBITMQ_HOST: localhost
        TEST_RABBITMQ_PORT: 5672
        TEST_RABBITMQ_URL: amqp://guest:guest@localhost:5672
        TEST_REDIS_HOST: localhost
        TEST_REDIS_PORT: 6379
