name: CI

on:
  push:
    branches:
      - main
      - ahayworth/move-builds-around-idk
  pull_request:
    branches:
      - main

jobs:
  test_fast:
    if: ${{ github.repository == 'ahayworth/opentelemetry-ruby' }}
    name: "Test ruby 3.1"
    uses: ./.github/workflows/test_gem.yml
    with:
      rubies: "3.1"


  test_slow:
    needs: test_fast
    if: ${{ github.repository == 'ahayworth/opentelemetry-ruby' }}
    name: "Test other rubies"
    uses: ./.github/workflows/test_gem.yml
    with:
      rubies: "2.7,3.0,jruby"
