name: Test Gem

on:
  workflow_call:
    inputs:
      rubies:
        description: Ruby version to use, as comma-separated string
        required: false
        type: string
        default: "3.1"

jobs:
  build_matrix:
    name: Build testing matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build_matrix.outputs.matrix }}
    steps:
      - id: build_matrix
        run: |
          matrix=$(ruby -rjson -rpathname -e "
            rubies = '${{ input.rubies }}'.split(',')
            all_gems = Pathname.glob('**/opentelemetry-*.gemspec')
            puts all_gems.each_with_object([]) do |path, a|
             rubies.each do |r|
                a << {
                  gem:  path.basename.sub('.gemspec', ''),
                  path: path.dirname,
                  ruby: r,
                }
              end
            end.to_json
          ")
          echo "::set-output name=matrix::${matrix}"

  test_gems:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.build_matrix.outputs.matrix) }}
        exclude:
          # depends on protobuf, which does not work on JRuby
          - ruby: jruby
            gem: opentelemetry-exporter-otlp
    name: ${{ matrix.gem }}@${{ matrix.ruby }}

    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      kafka:
        image: confluentinc/cp-kafka:latest
        ports:
          - 9092:9092
          - 29092:29092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      memcached:
        image: memcached:alpine
        ports:
          - 11211:11211
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
      redis:
        image: bitnami/redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_PASSWORD: "passw0rd"
      mysql:
        image: mysql:5.6
        env:
          MYSQL_DATABASE: mysql
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: mysql
          MYSQL_USER: mysql
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      rabbitmq:
        image: rabbitmq:3.8-alpine
        ports:
          - "5672:5672"
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
          working-directory: "${{ matrix.path }}"
          cache-version: 1
      - name: Install Appraisals
        working-directory: "${{ matrix.path }}"
        if: hashFiles('Appraisals') != ''
        run: |
          bundle exec appraisal install
      - name: Run tests
        working-directory: "${{ matrix.path }}"
        env:
          JRUBY_OPTS: --debug
          TEST_KAFKA_HOST: "127.0.0.1"
          TEST_KAFKA_PORT: 29092
          TEST_MYSQL_HOST: "127.0.0.1"
          TEST_MYSQL_PORT: 3306
          TEST_MYSQL_USER: mysql
          TEST_MYSQL_PASSWORD: mysql
          TEST_POSTGRES_PASSWORD: postgres
          TEST_POSTGRES_USER: postgres
          TEST_POSTGRES_HOST: localhost
          TEST_POSTGRES_PORT: 5432
          TEST_POSTGRES_DB: postgres
          TEST_MEMCACHED_HOST: localhost
          TEST_MEMCACHED_PORT: 11211
          TEST_MONGODB_HOST: localhost
          TEST_MONGODB_PORT: 27017
          TEST_RABBITMQ_HOST: localhost
          TEST_RABBITMQ_PORT: 5672
          TEST_RABBITMQ_URL: amqp://guest:guest@localhost:5672
          TEST_REDIS_HOST: localhost
          TEST_REDIS_PORT: 6379
        run: |
          if [[ -f Appraisals ]]; then
            bundle exec appraisal rake test
          else
            bundle exec rake test
          fi
      # - name: Rubocop
      #   working-directory: "${{ matrix.path }}"
      #   run: bundle exec rake rubocop
      - name: YARD
        working-directory: "${{ matrix.path }}"
        run: bundle exec rake yard
      - name: Build gem
        working-directory: "${{ matrix.path }}"
        run: gem build ${{ matrix.gem }}.gemspec
